name: Import Solution

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Source environment (dev, uat, prev, prod, hotfix)'
        required: true
        type: choice
        options:
          - dev
          - uat
          - prev
          - prod
          - hotfix

      branch:
        description: 'Target Git branch to update (dev, uat, prev, prod, hotfix)'
        required: true
        type: choice
        options:
          - dev
          - uat
          - prev
          - prod
          - hotfix

      solution_name:
        description: 'Name of the solution to export (logical name)'
        required: true

jobs:
  export-and-sync:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: ${{ secrets.POWER_PLATFORM_CLIENT_ID }}
      TENANT_ID: ${{ secrets.POWER_PLATFORM_TENANT_ID }}
      CLIENT_SECRET: ${{ secrets.POWER_PLATFORM_CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set environment URL
        run: |
          case "${{ github.event.inputs.environment }}" in
            dev)
              echo "ENV_URL=${{ secrets.DEV_ENV_URL }}" >> $GITHUB_ENV
              ;;
            uat)
              echo "ENV_URL=${{ secrets.UAT_ENV_URL }}" >> $GITHUB_ENV
              ;;
            prev)
              echo "ENV_URL=${{ secrets.PREV_ENV_URL }}" >> $GITHUB_ENV
              ;;
            prod)
              echo "ENV_URL=${{ secrets.PROD_ENV_URL }}" >> $GITHUB_ENV
              ;;
            hotfix)
              echo "ENV_URL=${{ secrets.HOTFIX_ENV_URL }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Invalid environment: ${{ github.event.inputs.environment }}"; exit 1
              ;;
          esac

      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Export solution from Power Platform (unmanaged)
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ env.ENV_URL }}
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ env.CLIENT_SECRET }}
          tenant-id: ${{ env.TENANT_ID }}
          solution-name: ${{ github.event.inputs.solution_name }}
          solution-output-file: exported_solution.zip
          managed: false

      - name: Switch to target branch
        run: |
          git fetch
          git checkout ${{ github.event.inputs.branch }}

      - name: Clean repository before unpacking (preserve .git and .github)
        run: |
          find . -maxdepth 1 ! -name . -a ! -name .git -a ! -name .github -exec rm -rf {} +

      - name: Unpack solution using PAC CLI
        run: |
          pac solution unpack --zipfile exported_solution.zip --folder . --allowDelete

      - name: Remove exported ZIP file
        run: rm -f exported_solution.zip

      - name: Commit and push all files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Export and unpack solution '${{ github.event.inputs.solution_name }}' from '${{ github.event.inputs.environment }}'"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.event.inputs.branch }}
          fi
